CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_PWM=y

# For MPU6050
# Example:
# https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/sensor/mpu6050/prj.conf
CONFIG_I2C=y
CONFIG_SENSOR=y

CONFIG_MPU6050_TRIGGER_GLOBAL_THREAD=y

